name: Sylius GrumPHP CI

on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up PHP
              uses: actions/setup-php@v1
              with:
                  php-version: 8.1

            - name: Install dependencies
              run: |
                  composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts

            - name: Run GrumPHP
              run: |
                  vendor/bin/grumphp run
